const puppeteer = require("puppeteer");
const fs = require("fs");
const PDFDocument = require("pdfkit");
const path = require("path");

const downloadDir = path.join(__dirname, "../downloads");

// Ensure the downloads directory exists
if (!fs.existsSync(downloadDir)) {
  fs.mkdirSync(downloadDir);
}

function saveAsText(summary, fileName) {
  const filePath = path.join(downloadDir, `${fileName}.txt`);
  fs.writeFileSync(filePath, summary);
  return filePath;
}


const saveAsPDF = async (summary, fileName) => {
  const filePath = path.join(downloadDir, `${fileName}.pdf`);
  // const styledSummary = summary.replace(/(important|critical|note)/gi, (match) => {
  //   return `<span class="highlight">${match}</span>`;
  // });
const formattedSummary = summary
  .replace(/## (.+)/g, '<h2><strong>$1</strong></h2>')  // bold + heading
  .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')     // bold text
  .split('\n')                                           // split lines
  .map(line => `<p>${line}</p>`)                         // wrap each line in <p>
  .join('');

  const htmlContent = `
    <html>
    <head>
      <style>
        body {
          font-family: "Helvetica", sans-serif;
          margin: 40px;
        }
        .watermark {
          position: fixed;
          top: 40%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-30deg);
          font-size: 100px;
          font-weight: bold;
          color: rgba(150, 150, 150, 0.1); 
          white-space: nowrap;
          z-index: 0;
          pointer-events: none;
          user-select: none;
        }
        h1 {
          text-align: center;
          color: #2e6da4;
        }
        .spacer {
  height: 100px; /* adjust based on footer height */
}

        .summary {
          font-size: 16px;
          line-height: 1.5;
          color: #333;
          background-color: #f9f9f9;
          padding-bottom: 100px;
        }
        footer {
          position: fixed;
          bottom: 5px;
          left: 40px;
          font-size: 12px;
          color: #888;
        }
      </style>
    </head>
    <body>
    <div class="watermark">DocSide</div>
      <h1>Summary Report</h1>
      <div class="summary">${formattedSummary}</div>
      <div class="spacer"></div>

      <footer>Generated by DocSide ${new Date().getFullYear()}</footer>
    </body>
    </html>
  `;

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });

  await page.pdf({
    path: filePath,
    format: "A4",
    margin: { top: "40px", bottom: "60px", left: "40px", right: "40px" }
  });

  await browser.close();
  return filePath;
};

module.exports = { saveAsText, saveAsPDF };
