const puppeteer = require("puppeteer");
const fs = require("fs");
const PDFDocument = require("pdfkit");
const path = require("path");

const downloadDir = path.join(__dirname, "../downloads");
if (!fs.existsSync(downloadDir)) {
  fs.mkdirSync(downloadDir);
}

function saveAsText(summary, fileName) {
  const filePath = path.join(downloadDir, `${fileName}.txt`);
  fs.writeFileSync(filePath, summary);
  return filePath;
}


const saveAsPDF = async (summary, fileName) => {
const filePath = path.join(downloadDir, `${fileName}.pdf`);
const logoPath = path.resolve(__dirname, '../public/Logo.png');
const logoData = fs.readFileSync(logoPath).toString('base64');
const logoUrl = `data:image/png;base64,${logoData}`;
const formattedSummary = summary
  .replace(/## (.+)/g, '<h2><strong>$1</strong></h2>')  
  .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')    
  .split('\n')                                         
  .map(line => `<p>${line}</p>`)                        
  .join('');

  const htmlContent = `
    <html>
    <head>
      <style>
        body {
          font-family: "Helvetica", sans-serif;
          margin: 40px;
        }
        .watermark {
          position: fixed;
          top: 40%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-30deg);
          font-size: 100px;
          font-weight: bold;
          color: rgba(150, 150, 150, 0.1); 
          white-space: nowrap;
          z-index: 0;
          pointer-events: none;
          user-select: none;
        }
        h1 {
          text-align: center;
          color: #2e6da4;
        }
        .summary {
          font-size: 16px;
          line-height: 1.5;
          color: #333;
          background-color: #f9f9f9;
          
        }
        footer {
          background: #333;
          color: white;
          text-align: center;
          padding: 2rem;
          padding-bottom: 2px;
        }
        img{
          height: 40px;
          padding-top: 2px;
          padding-left: 290px;
        }
      </style>
    </head>
    <body>
    <div class="watermark">DocSide</div>
      <h1>Summary Report</h1>
      <div class="summary">${formattedSummary}</div>
      <div class="spacer"></div>
      <footer>Generated by DocSide ${new Date().getFullYear()}
      </footer>
      <img src="${logoUrl}" alt="Logo">

    </body>
    </html>
  `;

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });

  await page.pdf({
    path: filePath,
    format: "A4",
    margin: { top: "40px", bottom: "60px", left: "40px", right: "40px" },
    footerTemplate: `
    <div style="width:100%;text-align:center;font-size:14p ;position:fixed">
      <span class="footer-text">
        <script>
          if (pageNumber === totalPages) {
            document.write('Generated by DocSide ${new Date().getFullYear()}');
          }
        </script>
      </span>
    </div>
  `,
  });

  await browser.close();
  return filePath;
};

module.exports = { saveAsText, saveAsPDF };
